@echo off
REM ****************************************************************************
REM Vivado (TM) v2024.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Wed Jun 17 06:14:13 -0400 2026
REM SW Build 5239630 on Fri Nov 08 22:35:27 MST 2024
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim TB1_Interleave_X2_LTC2315_12_behav -key {Behavioral:sim_1:Functional:TB1_Interleave_X2_LTC2315_12} -tclbatch TB1_Interleave_X2_LTC2315_12.tcl -view C:/IMR_Projects/IMR/Custom_RTL/Interleave_Dual_LTC2315-12/TB1_Interleave_X2_LTC2315_12_behav.wcfg -log simulate.log"
call xsim  TB1_Interleave_X2_LTC2315_12_behav -key {Behavioral:sim_1:Functional:TB1_Interleave_X2_LTC2315_12} -tclbatch TB1_Interleave_X2_LTC2315_12.tcl -view C:/IMR_Projects/IMR/Custom_RTL/Interleave_Dual_LTC2315-12/TB1_Interleave_X2_LTC2315_12_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
